@ascent_lab_api_HostAddress = https://localhost:8443

GET {{ascent_lab_api_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{ascent_lab_api_HostAddress}}/swagger/
Accept: application/json

###
